### ISSUE TITLE
I can't save map for community races 

### ISSUE THREAD

**Issue by tedomedo** [oldnapalm/CommunityRaces#11] opened 2023-11-02 18:19 UTC
I have community races mod 1.5 and map editor 2.15. I create map for community races but when i want to save, i see errors
![slika](https://github.com/Guad/NativeUI/assets/52840688/80ced703-a3e2-49aa-9466-599ffdf537d5)
In ScriptHookVDotNet.log i see this: 
[23:15:50] [ERROR] Caught fatal unhandled exception:
System.MissingFieldException: Field not found: 'MapEditor.MapObject.Texture'.
   at CommunityRaces.CommunityRaces.SaveMap(Map map, String filename)
   at MapEditor.MapEditor.<.ctor>b__44_0(UIMenu m, UIMenuItem it, Int32 i)
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.UIMenu.ProcessControl(Keys key)
   at NativeUI.MenuPool.ProcessControl()
   at NativeUI.MenuPool.ProcessMenus()
   at MapEditor.MapEditor.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[23:15:50] [ERROR] The exception was thrown while executing the script MapEditor.MapEditor.
[23:15:50] [WARNING] Aborted script MapEditor.MapEditor.

Any way to fix that? Map editor works for maps not related to community races.

**Comment by oldnapalm** [comment] 2023-11-02 18:48
I can't reproduce this error. Make sure you have all files from the latest version of both mods.

https://github.com/oldnapalm/MapEditor/releases/tag/v2.15

`MapObject.Texture` was introduced in my update, it looks like you are using an older version.

**Comment by tedomedo** [comment] 2023-11-02 21:02
Oh, i see now that map editor 2.15 .zip from github is different than .zip from https://www.gta5-mods.com/scripts/map-editor-oldnapalm
Do i have to move entire folder MapEditor-2.15 from .zip into scripts folder?

**Comment by oldnapalm** [comment] 2023-11-02 21:35
> Oh, i see now that map editor 2.15 .zip from github is different than .zip from https://www.gta5-mods.com/scripts/map-editor-oldnapalm

No, it's the same file

![2023-11-02 18_33_30-MapEditor-2 15 zip](https://github.com/oldnapalm/CommunityRaces/assets/38410858/1ea31d59-58d6-4ef0-bbb9-7f92df0e39b4)

> Do i have to move entire folder MapEditor-2.15 from .zip into scripts folder?

Yes, extract all the zip contents to your scripts folder.

**Comment by tedomedo** [comment] 2023-11-02 22:09
2205cd-MapEditor-2.15.zip from gta v mods doesn't have the same files as MapEditor-2.15.zip from github. 
![slika](https://github.com/oldnapalm/CommunityRaces/assets/52840688/b4f10383-8d7a-426c-8c2b-fcfb2a371361)

**Comment by oldnapalm** [comment] 2023-11-02 22:15
You downloaded the repository (source code). You should download the release (link I posted above which is the same file as gta5-mods.com).

**Comment by oldnapalm** [comment] 2023-11-02 22:21
Your issue is with MapEditor, please use https://github.com/oldnapalm/MapEditor/issues/4

The problem you posted here (`System.MissingFieldException: Field not found: 'MapEditor.MapObject.Texture'`) happened because you were using the wrong MapEditor version.

**Comment by tedomedo** [comment] 2023-11-02 22:46
I closed "issue" there, can we continue here, oldnapalm?
I use your 2205cd-MapEditor-2.15.zip. Before i was using map editor 2.13 and community races 1.3, saving worked but racing didn't, when race started, i was not in a vehicle. That's why i tried with versions 1.5 + 2.15.  Creating maps which are not related to community races works well.

**Comment by oldnapalm** [comment] 2023-11-02 22:53
- Download https://github.com/scripthookvdotnet/scripthookvdotnet/releases/tag/v3.6.0 and extract ScriptHookVDotNet.zip to your GTA 5 folder
- Download https://github.com/oldnapalm/CommunityRaces/releases/tag/v1.7 and extract communityraces-1.7.zip to your scripts folder
- Download https://github.com/oldnapalm/MapEditor/releases/tag/v2.15 and extract MapEditor-2.15.zip to your scripts folder

It should work, just tested it. If it doesn't work for you, post the file ScriptHookVDotNet.log from your GTA 5 folder.

**Comment by tedomedo** [comment] 2023-11-02 22:56
Is your map editor from here different that from gta v mods sites? Both have the same sites. I'm from Europe, i have to go to bed :) I will "report" tomorrow. Thanks. Hope i'm not pissing you.

**Comment by oldnapalm** [comment] 2023-11-02 22:59
Like I said before, the files are identical, I uploaded the same file here and there. The only difference is the name because gta5-mods added `2205cd-`.

**Comment by tedomedo** [comment] 2023-11-03 08:32
Today i downloaded, unzipped your 3 zips and replaced files. Map editor doesn't show error, it show text "map sent to external mod for saving" but then map editor freezes. I have to reload scripts. After that, my map isn't in Races folder.  Text in scripthookdotnet.log:
[09:46:49] [ERROR] Caught fatal unhandled exception:
System.MissingFieldException: Field not found: 'MapEditor.MapObject.Texture'.
   at CommunityRaces.CommunityRaces.SaveMap(Map map, String filename)
   at MapEditor.MapEditor.<.ctor>b__44_0(UIMenu m, UIMenuItem it, Int32 i)
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.UIMenu.ProcessControl(Keys key)
   at NativeUI.MenuPool.ProcessControl()
   at NativeUI.MenuPool.ProcessMenus()
   at MapEditor.MapEditor.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[09:46:49] [ERROR] The exception was thrown while executing the script MapEditor.MapEditor.
[09:46:49] [WARNING] Aborted script MapEditor.MapEditor.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()

**Comment by oldnapalm** [comment] 2023-11-03 11:32
This is the same error, it indicates you are still using version 2.13.

Backup your scripts folder, create a new one and add only the files from communityraces-1.7.zip and MapEditor-2.15.zip.

If you still have the error, attach the full ScriptHookVDotNet.log.

**Comment by tedomedo** [comment] 2023-11-03 11:46
[12:37:57] [DEBUG] Loading API from .\ScriptHookVDotNet2.dll ...
[12:37:57] [DEBUG] Loading API from .\ScriptHookVDotNet3.dll ...
[12:37:58] [DEBUG] Loading scripts from E:\Games\Grand Theft Auto V\scripts ...
[12:37:59] [DEBUG] Loading assembly ClearScript.dll ...
[12:37:59] [INFO] Found 0 script(s) in ClearScript.dll.
[12:37:59] [DEBUG] Loading assembly CommunityRaces.dll ...
[12:38:00] [INFO] Found 1 script(s) in CommunityRaces.dll resolved to API 2.11.6.
[12:38:00] [DEBUG] Loading assembly CustomReticle.dll ...
[12:38:00] [WARNING] Resolving API version 0.0.0 referenced in CustomReticle.dll.
[12:38:00] [INFO] Found 2 script(s) in CustomReticle.dll resolved to API 2.11.6.
[12:38:00] [DEBUG] Loading assembly Dismemberment.dll ...
[12:38:00] [INFO] Found 2 script(s) in Dismemberment.dll resolved to API 2.11.6.
[12:38:00] [DEBUG] Loading assembly GTACoOp.dll ...
[12:38:00] [INFO] Found 2 script(s) in GTACoOp.dll resolved to API 2.11.6.
[12:38:00] [DEBUG] Loading assembly Lidgren.Network.MultiTarget.dll ...
[12:38:00] [INFO] Found 0 script(s) in Lidgren.Network.MultiTarget.dll.
[12:38:00] [DEBUG] Loading assembly MapEditor.dll ...
[12:38:00] [WARNING] Resolving API version 0.0.0 referenced in MapEditor.dll.
[12:38:00] [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.
[12:38:00] [DEBUG] Loading assembly MaxMind.Db.dll ...
[12:38:00] [INFO] Found 0 script(s) in MaxMind.Db.dll.
[12:38:00] [DEBUG] Loading assembly MaxMind.GeoIP2.dll ...
[12:38:00] [INFO] Found 0 script(s) in MaxMind.GeoIP2.dll.
[12:38:00] [DEBUG] Loading assembly NativeUI.dll ...
[12:38:01] [INFO] Found 1 script(s) in NativeUI.dll resolved to API 2.11.6.
[12:38:01] [DEBUG] Loading assembly Newtonsoft.Json.dll ...
[12:38:01] [INFO] Found 0 script(s) in Newtonsoft.Json.dll.
[12:38:01] [DEBUG] Loading assembly protobuf-net.dll ...
[12:38:01] [INFO] Found 0 script(s) in protobuf-net.dll.
[12:38:01] [DEBUG] Loading assembly Street Racing Editor.dll ...
[12:38:01] [INFO] Found 1 script(s) in Street Racing Editor.dll resolved to API 2.11.6.
[12:38:01] [DEBUG] Loading assembly Street Racing.dll ...
[12:38:01] [INFO] Found 1 script(s) in Street Racing.dll resolved to API 2.11.6.
[12:38:01] [DEBUG] Instantiating script CommunityRaces.CommunityRaces ...
[12:38:05] [INFO] Started script CommunityRaces.CommunityRaces.
[12:38:05] [DEBUG] Instantiating script CustomReticle.Main ...
[12:38:05] [INFO] Started script CustomReticle.Main.
[12:38:05] [DEBUG] Instantiating script CustomReticle.Menu ...
[12:38:06] [INFO] Started script CustomReticle.Menu.
[12:38:06] [DEBUG] Instantiating script Dismemberment.Main ...
[12:38:06] [INFO] Started script Dismemberment.Main.
[12:38:06] [DEBUG] Instantiating script Dismemberment.Settings ...
[12:38:06] [INFO] Started script Dismemberment.Settings.
[12:38:06] [DEBUG] Instantiating script GTACoOp.Main ...
[12:38:06] [INFO] Started script GTACoOp.Main.
[12:38:06] [DEBUG] Instantiating script GTACoOp.PedThread ...
[12:38:06] [INFO] Started script GTACoOp.PedThread.
[12:38:06] [DEBUG] Instantiating script MapEditor.JavascriptHook ...
[12:38:06] [INFO] Started script MapEditor.JavascriptHook.
[12:38:06] [DEBUG] Instantiating script MapEditor.MapEditor ...
[12:38:07] [INFO] Started script MapEditor.MapEditor.
[12:38:07] [DEBUG] Instantiating script NativeUI.BigMessageThread ...
[12:38:07] [INFO] Started script NativeUI.BigMessageThread.
[12:38:07] [DEBUG] Instantiating script StreetRacesEditor ...
[12:38:07] [INFO] Started script StreetRacesEditor.
[12:38:07] [DEBUG] Instantiating script Street_Races.StreetRaces ...
[12:38:07] [INFO] Started script Street_Races.StreetRaces.
[12:41:17] [ERROR] Caught fatal unhandled exception:
System.MissingFieldException: Field not found: 'MapEditor.MapObject.Texture'.
   at CommunityRaces.CommunityRaces.SaveMap(Map map, String filename)
   at MapEditor.MapEditor.<.ctor>b__44_0(UIMenu m, UIMenuItem it, Int32 i)
   at NativeUI.UIMenu.SelectItem()
   at NativeUI.UIMenu.ProcessControl(Keys key)
   at NativeUI.MenuPool.ProcessControl()
   at NativeUI.MenuPool.ProcessMenus()
   at MapEditor.MapEditor.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.DoTick()
[12:41:17] [ERROR] The exception was thrown while executing the script MapEditor.MapEditor.
[12:41:17] [WARNING] Aborted script MapEditor.MapEditor.
   at System.Threading.Thread.AbortInternal()
   at System.Threading.Thread.Abort()
   at SHVDN.Script.Abort()
   at SHVDN.Script.DoTick()
   at SHVDN.Script.MainLoop()

I'm using map editor 2.15, community races 1.7, ScriptHookVDotNet 3.6.0, NativeUI 1.9.

**Comment by oldnapalm** [comment] 2023-11-03 12:01
This shows you are using MapEditor 2.13

>[12:38:00] [DEBUG] Loading assembly MapEditor.dll ...
[12:38:00] [WARNING] Resolving API version 0.0.0 referenced in MapEditor.dll.
[12:38:00] [INFO] Found 2 script(s) in MapEditor.dll resolved to API 2.11.6.

In version 2.15 that warning message doesn't appear.

**Comment by tedomedo** [comment] 2023-11-03 12:08
I deleted all files about map editor then unzipped all files from your 2205cd-MapEditor-2.15.zip, 
I use 2.15. I see in .zip that MapEditor.dll is from year 2021, everything else (except NativeUI) is from year 2016.

**Comment by oldnapalm** [comment] 2023-11-03 12:16
Sorry but there's nothing else I can do since you didn't do what I suggested

> Backup your scripts folder, create a new one and add only the files from communityraces-1.7.zip and MapEditor-2.15.zip.
> 
> If you still have the error, attach the full ScriptHookVDotNet.log.

Your log shows you have various other mods in the scripts folder and that warning message shows MapEditor.dll is not the version from my zip because it does not reference API version 0.0.0.

**Comment by tedomedo** [comment] 2023-11-03 13:00
I zipped scripts folder, created new one, unzipped everything about map editor and community races. I can save map for community races now. Thanks. I'm adding other mods individually in order to check if map editor works with other maps. 

Since it works now, i have to ask about spawning vehicles. Many vehicles in map editor don't have the same name as displayed name when we enter a vehicle. VehicleList.ini file is old 7 years, It doesn't have as many vehicles as I can get them with trainer. All vehicles should be in groups, e. g. all supercars together. Please, do something about that, oldnapalm.

**Comment by oldnapalm** [comment] 2023-11-03 15:46
You can find updated vehicles list on the internet, like https://www.gta5-mods.com/tools/updated-vehicle-list-for-map-editor

**Closed as completed by oldnapalm** 2023-11-03 15:46 UTC

**Comment by tedomedo** [comment] 2023-11-03 16:09
Yeah, i know about that. 
Thanks for support. Case closed. Over and out :)
